const db = require("./connection");
const {
  User,
  Product,
  Category,
  WomenProductItems,
  MenProductItems,
} = require("../models");

db.once("open", async () => {
  //for seeding Categories
  await Category.deleteMany();
  const categories = await Category.insertMany([
    { name: "women" },
    { name: "men" },
    // { name: "kids" },
  ]);
  console.log("category seeded");
  //for seeding womenprodcutitem
  await WomenProductItems.deleteMany();
  const womenProductItems = await WomenProductItems.insertMany([
    { name: "jacket" },
    { name: "blouse" },
    { name: "T-shirt" },
    { name: "sweatshirt" },
    { name: "pants" },
    { name: "shorts" },
    { name: "skirt" },
  ]);
  console.log("womenProductItems seeded");
  //for seeding menprodcutitem
  await MenProductItems.deleteMany();
  const menProductItems = await MenProductItems.insertMany([
    // { name: "jacket" },
    { name: "blouse" },
    { name: "T-shirt" },
    { name: "hoodie" },
    { name: "pants" },
    { name: "shorts" },
    { name: "sweatshirt" },
  ]);
  console.log("menProductItems seeded");

  //for seeding women products
  await Product.deleteMany();
  const products = await Product.insertMany([
    //for women jacket
    {
      name: "jacket",
      price: 50,
      color: "blue",
      size: "large",
      quantity: 2,
      image: "women-jacket-blue.jpg",
      category: "women",
    },
    {
      name: "jacket",
      price: 50,
      color: "black",
      size: "small",
      quantity: 2,
      image: "women-jacket-blackk.jpg",
      category: "women",
    },
    {
      name: "jacket",
      price: 100,
      color: "white",
      size: "medium",
      quantity: 2,
      image: "women-jacket-white.jpg",
      category: "women",
    },
    {
      name: "jacket",
      price: 50,
      color: "brown",
      size: "large",
      quantity: 2,
      image: "women-jacket-brown.jpg",
      category: "women",
    },
    {
      name: "jacket",
      price: 150,
      color: "green",
      size: "small",
      quantity: 2,
      image: "women-jacket-green.jpg",
      category: "women",
    },
    {
      name: "jacket",
      price: 125,
      color: "black",
      size: "medium",
      quantity: 2,
      image: "women-jacket-pureblack.jpg",
      category: "women",
    },
    {
      name: "jacket",
      price: 56,
      color: "pink",
      size: "small",
      quantity: 2,
      image: "women-jacket-pink.jpg",
      category: "women",
    },
    {
      name: "jacket",
      price: 78,
      color: "blue",
      size: "medium",
      quantity: 2,
      image: "women-jacket-darkkblue.jpg",
      category: "women",
    },
    {
      name: "jacket",
      price: 83,
      color: "blue",
      size: "small",
      quantity: 2,
      image: "women-jacket-darkblue.jpg",
      category: "women",
    },
    {
      name: "jacket",
      price: 200,
      color: "black",
      size: "large",
      quantity: 2,
      image: "women-jacket-black.jpg",
      category: "women",
    },
    //for women tops
    {
      name: "blouse",
      price: 100,
      color: "black",
      size: "large",
      quantity: 2,
      image: "women-blouse-black.jpg",
      category: "women",
    },
    {
      name: "blouse",
      price: 120,
      color: "brown",
      size: "small",
      quantity: 3,
      image: "women-blouse-brown.jpg",
      category: "women",
    },
    {
      name: "blouse",
      price: 150,
      color: "blue",
      size: "medium",
      quantity: 5,
      image: "women-blouse-blue.jpg",
      category: "women",
    },
    {
      name: "T-shirt",
      price: 35,
      color: "white",
      size: "small",
      quantity: 11,
      image: "women-T-shirt-white.jpg",
      category: "women",
    },
    {
      name: "T-shirt",
      price: 46,
      color: "black",
      size: "large",
      quantity: 2,
      image: "women-T-shirt-black.jpg",
      category: "women",
    },
    {
      name: "T-shirt",
      price: 23,
      color: "brown",
      size: "samll",
      quantity: 4,
      image: "women-T-shirt-brown.jpg",
      category: "women",
    },
    {
      name: "T-shirt",
      price: 12,
      color: "blue",
      size: "medium",
      quantity: 6,
      image: "women-T-shirt-blue.jpg",
      category: "women",
    },
    {
      name: "T-shirt",
      price: 30,
      color: "white",
      size: "small",
      quantity: 10,
      image: "women-T-shirt-whitee.jpg",
      category: "women",
    },
    {
      name: "T-shirt",
      price: 76,
      color: "black",
      size: "large",
      quantity: 2,
      image: "women-T-shirt-blackk.jpg",
      category: "women",
    },
    {
      name: "T-shirt",
      price: 83,
      color: "pink",
      size: "large",
      quantity: 2,
      image: "women-T-shirt-pink.jpg",
      category: "women",
    },
    {
      name: "T-shirt",
      price: 42,
      color: "green",
      size: "small",
      quantity: 3,
      image: "women-T-shirt-green.jpg",
      category: "women",
    },
    //for women bottom
    {
      name: "skirt",
      price: 40,
      color: "blue",
      size: "small",
      quantity: 6,
      image: "women-skirt-blue.jpg",
      category: "women",
    },
    {
      name: "skirt",
      price: 32,
      color: "black",
      size: "small",
      quantity: 3,
      image: "women-skirt-whiteee.jpg",
      category: "women",
    },
    {
      name: "skirt",
      price: 36,
      color: "black",
      size: "medium",
      quantity: 2,
      image: "women-skirt-black.jpg",
      category: "women",
    },
    {
      name: "skirt",
      price: 38,
      color: "white",
      size: "small",
      quantity: 4,
      image: "women-skirt-white.jpg",
      category: "women",
    },
    {
      name: "skirt",
      price: 42,
      color: "white",
      size: "large",
      quantity: 7,
      image: "women-skirt-whitee.jpg",
      category: "women",
    },
    {
      name: "skirt",
      price: 44,
      color: "black",
      size: "large",
      quantity: 5,
      image: "women-skirt-blackk.jpg",
      category: "women",
    },
    {
      name: "pants",
      price: 25,
      color: "black",
      size: "small",
      quantity: 2,
      image: "women-pants-blackkk.jpg",
      category: "women",
    },
    {
      name: "pants",
      price: 25,
      color: "black",
      size: "medium",
      quantity: 2,
      image: "women-pants-blackkkk.jpg",
      category: "women",
    },
    {
      name: "pants",
      price: 25,
      color: "black",
      size: "large",
      quantity: 7,
      image: "women-pants-black.jpg",
      category: "women",
    },
    {
      name: "pants",
      price: 25,
      color: "brown",
      size: "large",
      quantity: 4,
      image: "women-pants-brown.jpg",
      category: "women",
    },
    {
      name: "pants",
      price: 25,
      color: "brown",
      size: "small",
      quantity: 3,
      image: "women-pants-brownn.jpg",
      category: "women",
    },
    {
      name: "pants",
      price: 25,
      color: "brown",
      size: "medium",
      quantity: 5,
      image: "women-pants-brownnn.jpg",
      category: "women",
    },
    {
      name: "pants",
      price: 25,
      color: "blue",
      size: "medium",
      quantity: 6,
      image: "women-pants-blueee.jpg",
      category: "women",
    },
    {
      name: "pants",
      price: 25,
      color: "blue",
      size: "medium",
      quantity: 9,
      image: "women-pants-blue.jpg",
      category: "women",
    },
    {
      name: "pants",
      price: 25,
      color: "grey",
      size: "small",
      quantity: 1,
      image: "women-pants-greyy.jpg",
      category: "women",
    },
    {
      name: "pants",
      price: 25,
      color: "grey",
      size: "medium",
      quantity: 8,
      image: "women-pants-grey.jpg",
      category: "women",
    },
    {
      name: "pants",
      price: 25,
      color: "green",
      size: "medium",
      quantity: 4,
      image: "women-pants-greenn.jpg",
      category: "women",
    },
    {
      name: "pants",
      price: 25,
      color: "green",
      size: "small",
      quantity: 2,
      image: "women-pants-green.jpg",
      category: "women",
    },
    {
      name: "pants",
      price: 25,
      color: "pink",
      size: "medium",
      quantity: 7,
      image: "women-pants-pinkk.jpg",
      category: "women",
    },
    {
      name: "pants",
      price: 25,
      color: "pink",
      size: "small",
      quantity: 3,
      image: "women-pants-pink.jpg",
      category: "women",
    },
    {
      name: "pants",
      price: 25,
      color: "orange",
      size: "medium",
      quantity: 6,
      image: "women-pants-orangee.jpg",
      category: "women",
    },
    {
      name: "pants",
      price: 25,
      color: "orange",
      size: "small",
      quantity: 5,
      image: "women-pants-orange.jpg",
      category: "women",
    },
    {
      name: "shorts",
      price: 25,
      color: "pink",
      size: "medium",
      quantity: 7,
      image: "women-shorts-pink.jpg",
      category: "women",
    },
    {
      name: "shorts",
      price: 25,
      color: "pink",
      size: "small",
      quantity: 3,
      image: "women-shorts-pinkk.jpg",
      category: "women",
    },
    {
      name: "shorts",
      price: 25,
      color: "orange",
      size: "medium",
      quantity: 6,
      image: "women-shorts-orange.jpg",
      category: "women",
    },
    {
      name: "shorts",
      price: 25,
      color: "green",
      size: "large",
      quantity: 5,
      image: "women-shorts-green.jpg",
      category: "women",
    },
    {
      name: "shorts",
      price: 25,
      color: "black",
      size: "medium",
      quantity: 3,
      image: "women-shorts-black.jpg",
      category: "women",
    },
    {
      name: "shorts",
      price: 25,
      color: "white",
      size: "small",
      quantity: 3,
      image: "women-shorts-white.jpg",
      category: "women",
    },
    //for women sweetshirt
    {
      name: "sweatshirt",
      price: 150,
      color: "orange",
      size: "medium",
      quantity: 6,
      image: "women-sweatshirt-orange.jpg",
      category: "women",
    },
    {
      name: "sweatshirt",
      price: 125,
      color: "green",
      size: "large",
      quantity: 5,
      image: "women-sweatshirt-green.jpg",
      category: "women",
    },
    {
      name: "sweatshirt",
      price: 100,
      color: "black",
      size: "medium",
      quantity: 3,
      image: "women-sweatshirt-black.jpg",
      category: "women",
    },
    {
      name: "sweatshirt",
      price: 140,
      color: "white",
      size: "small",
      quantity: 3,
      image: "women-sweatshirt-white.jpg",
      category: "women",
    },

    //for men products
    {
      name: "hoodie",
      price: 50,
      color: "blue",
      size: "large",
      quantity: 2,
      image: "men-hoodie-blue.jpg",
      category: "men",
    },
    {
      name: "hoodie",
      price: 50,
      color: "black",
      size: "small",
      quantity: 2,
      image: "men-hoodie-black.jpg",
      category: "men",
    },
    {
      name: "hoodie",
      price: 100,
      color: "white",
      size: "medium",
      quantity: 2,
      image: "men-hoodie-white.jpg",
      category: "men",
    },
    {
      name: "hoodie",
      price: 50,
      color: "brown",
      size: "large",
      quantity: 2,
      image: "men-hoodie-brown.jpg",
      category: "men",
    },
    {
      name: "hoodie",
      price: 150,
      color: "green",
      size: "small",
      quantity: 2,
      image: "men-hoodie-green.jpg",
      category: "men",
    },
    {
      name: "hoodie",
      price: 125,
      color: "black",
      size: "medium",
      quantity: 2,
      image: "men-hoodie-black.jpg",
      category: "men",
    },
    {
      name: "hoodie",
      price: 56,
      color: "pink",
      size: "small",
      quantity: 2,
      image: "men-hoodie-pink.jpg",
      category: "men",
    },
    {
      name: "hoodie",
      price: 78,
      color: "blue",
      size: "medium",
      quantity: 2,
      image: "men-hoodie-bluee.jpg",
      category: "men",
    },
    {
      name: "hoodie",
      price: 83,
      color: "blue",
      size: "small",
      quantity: 2,
      image: "men-hoodie-blueee.jpg",
      category: "men",
    },
    {
      name: "hoodie",
      price: 200,
      color: "black",
      size: "large",
      quantity: 2,
      image: "men-hoodie-blackk.jpg",
      category: "men",
    },
    //for men tops
    {
      name: "blouse",
      price: 100,
      color: "black",
      size: "large",
      quantity: 2,
      image: "men-blouse-black.jpg",
      category: "men",
    },
    {
      name: "blouse",
      price: 120,
      color: "brown",
      size: "samll",
      quantity: 3,
      image: "men-blouse-brown.jpg",
      category: "men",
    },
    {
      name: "blouse",
      price: 150,
      color: "blue",
      size: "medium",
      quantity: 5,
      image: "men-blouse-blue.jpg",
      category: "men",
    },
    {
      name: "T-shirt",
      price: 35,
      color: "white",
      size: "small",
      quantity: 11,
      image: "men-T-shirt-white.jpg",
      category: "men",
    },
    {
      name: "T-shirt",
      price: 46,
      color: "black",
      size: "large",
      quantity: 2,
      image: "men-T-shirt-black.jpg",
      category: "men",
    },
    {
      name: "T-shirt",
      price: 23,
      color: "brown",
      size: "samll",
      quantity: 4,
      image: "men-T-shirt-brown.jpg",
      category: "men",
    },
    {
      name: "T-shirt",
      price: 12,
      color: "blue",
      size: "medium",
      quantity: 6,
      image: "men-T-shirt-blue.jpg",
      category: "men",
    },
    {
      name: "T-shirt",
      price: 30,
      color: "white",
      size: "small",
      quantity: 10,
      image: "men-T-shirt-white.jpg",
      category: "men",
    },
    {
      name: "T-shirt",
      price: 76,
      color: "black",
      size: "large",
      quantity: 2,
      image: "men-T-shirt-black.jpg",
      category: "men",
    },
    {
      name: "T-shirt",
      price: 83,
      color: "pink",
      size: "large",
      quantity: 2,
      image: "men-T-shirt-pink.jpg",
      category: "men",
    },
    {
      name: "T-shirt",
      price: 42,
      color: "green",
      size: "small",
      quantity: 3,
      image: "men-T-shirt-green.jpg",
      category: "men",
    },
    //for men bottom
    {
      name: "pants",
      price: 25,
      color: "black",
      size: "small",
      quantity: 2,
      image: "men-pants-black.jpg",
      category: "men",
    },
    {
      name: "pants",
      price: 25,
      color: "black",
      size: "medium",
      quantity: 2,
      image: "men-pants-black.jpg",
      category: "men",
    },
    {
      name: "pants",
      price: 25,
      color: "black",
      size: "large",
      quantity: 7,
      image: "men-pants-black.jpg",
      category: "men",
    },
    {
      name: "pants",
      price: 25,
      color: "brown",
      size: "large",
      quantity: 4,
      image: "men-pants-brown.jpg",
      category: "men",
    },
    {
      name: "pants",
      price: 25,
      color: "brown",
      size: "small",
      quantity: 3,
      image: "men-pants-brown.jpg",
      category: "men",
    },
    {
      name: "pants",
      price: 25,
      color: "brown",
      size: "medium",
      quantity: 5,
      image: "men-pants-brown.jpg",
      category: "men",
    },
    {
      name: "pants",
      price: 25,
      color: "blue",
      size: "medium",
      quantity: 6,
      image: "men-pants-blue.jpg",
      category: "men",
    },
    {
      name: "pants",
      price: 25,
      color: "blue",
      size: "medium",
      quantity: 9,
      image: "men-pants-blue.jpg",
      category: "men",
    },
    {
      name: "pants",
      price: 25,
      color: "grey",
      size: "small",
      quantity: 1,
      image: "men-pants-grey.jpg",
      category: "men",
    },
    {
      name: "pants",
      price: 25,
      color: "grey",
      size: "medium",
      quantity: 8,
      image: "men-pants-grey.jpg",
      category: "men",
    },
    {
      name: "pants",
      price: 25,
      color: "green",
      size: "medium",
      quantity: 4,
      image: "men-pants-green.jpg",
      category: "men",
    },
    {
      name: "pants",
      price: 25,
      color: "green",
      size: "small",
      quantity: 2,
      image: "men-pants-green.jpg",
      category: "men",
    },
    {
      name: "pants",
      price: 25,
      color: "pink",
      size: "medium",
      quantity: 7,
      image: "men-pants-pink.jpg",
      category: "men",
    },
    {
      name: "pants",
      price: 25,
      color: "pink",
      size: "small",
      quantity: 3,
      image: "men-pants-pink.jpg",
      category: "men",
    },
    {
      name: "pants",
      price: 25,
      color: "orange",
      size: "medium",
      quantity: 6,
      image: "men-pants-orange.jpg",
      category: "men",
    },
    {
      name: "pants",
      price: 25,
      color: "orange",
      size: "small",
      quantity: 5,
      image: "men-pants-orange.jpg",
      category: "men",
    },
    {
      name: "shorts",
      price: 25,
      color: "pink",
      size: "medium",
      quantity: 7,
      image: "men-shorts-pink.jpg",
      category: "men",
    },
    {
      name: "shorts",
      price: 25,
      color: "pink",
      size: "small",
      quantity: 3,
      image: "men-shorts-pink.jpg",
      category: "men",
    },
    {
      name: "shorts",
      price: 25,
      color: "orange",
      size: "medium",
      quantity: 6,
      image: "men-shorts-orange.jpg",
      category: "men",
    },
    {
      name: "shorts",
      price: 25,
      color: "green",
      size: "large",
      quantity: 5,
      image: "men-shorts-green.jpg",
      category: "men",
    },
    {
      name: "shorts",
      price: 25,
      color: "black",
      size: "medium",
      quantity: 3,
      image: "men-shorts-black.jpg",
      category: "men",
    },
    {
      name: "shorts",
      price: 25,
      color: "white",
      size: "small",
      quantity: 3,
      image: "men-shorts-white.jpg",
      category: "men",
    },
    //for men sweetshirt
    {
      name: "sweatshirt",
      price: 180,
      color: "orange",
      size: "medium",
      quantity: 6,
      image: "men-sweatshirt-orange.jpg",
      category: "men",
    },
    {
      name: "sweatshirt",
      price: 135,
      color: "green",
      size: "large",
      quantity: 5,
      image: "men-sweatshirt-green.jpg",
      category: "men",
    },
    {
      name: "sweatshirt",
      price: 110,
      color: "black",
      size: "medium",
      quantity: 3,
      image: "men-sweatshirt-black.jpg",
      category: "men",
    },
    {
      name: "sweatshirt",
      price: 160,
      color: "white",
      size: "small",
      quantity: 3,
      image: "men-sweatshirt-white.jpg",
      category: "men",
    },
  ]);
  console.log("product seeded");

  //for seeding users
  await User.deleteMany();
  await User.create({
    firstName: "john",
    lastName: "doe",
    email: "johndoe@testmail.com",
    password: "password12345",
    // orders: [
    //   {
    //     products: [products[0]._id, products[0]._id, products[1]._id]
    //   }
    // ]
  });
  await User.create({
    firstName: "sam",
    lastName: "smith",
    email: "samsmith@testmail.com",
    password: "password12345",
  });

  console.log("user seeded");

  process.exit();
});
